platform :ios, "15.0"
use_frameworks! :linkage => :static

def pod_JSNetwork
  pod "JSNetwork", :path => "..", :subspecs => ['ExtensionForSwift', 'RequestForAFNetworking', 'RequestForAlamofire', 'Plugins']
end

target "JSNetworkExample" do
  # 网络请求
  pod_JSNetwork
  pod "QMUIKit"
  pod "PromisesObjC"
end

target "JSNetworkExampleTests" do
  pod_JSNetwork
end

target "JSNetworkExampleUITests" do
  pod_JSNetwork
end

def set_deployment_target(target)
  target.build_configurations.each do |config|
    config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.0"
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    set_deployment_target(target)
  end
end
